#!/anaconda3/bin/python3
#This script converts a DNA sequence (input) to RNA sequence (output) by substituting a "U" base for "T" bases in the original seq

DNA = 'TCCCGAGAAGAAGCTTAAACATCGAGGATTTGTTATTCACGTAGGCTGTGACCTTTCGTGTCTACGCCTGGGCCGATGAGCAACTACTAGAAGTGTGGTAGCAACGTGTTAGAGTGGGTACGCTCGTTGAGACAAACCAGGCATACAACTCTGCCAGGGTGTATAAATCCAATTAACTATGGGTTTCATGTTGCAAAATACTACAGGTTATACCAATAAGCCAGAGAGACAGGATGCCTTAGGATTTCGTTATTACTGGCGCGTATTAACATCAGTTGAGACCTCTGCGTGCGTCAGCATACAATCTGAAGGAGGACGTGAGGAAGGAGTGCATTCACCGGGCAAACGACGCCAGGAACCAACCTTTGTGTTGTGTACATAATACGGATAGGATCTAAGACTCCAATTTGTAAGGGAACAATGCGTAGTTCATTTTGGGGCCAAAGACCGCCCAAAGGCTGGCCCGGCACGTGCTATATCCTTTTGGGTTATTTTACATCACACTACGTGAGCCTGTATAAAATCGATTCCTTCAGCGATTCCCCTGTATTGTTATCGCGCGCCGTATAAGTCCGGCTCCCTCCCATGTACTTATCTTTGCCTTGACCTACTGAACTAGTACCTCCTGGTCCCACCCGCGGCTGCAGGGTATCCCATTCGTGGCTATACTCTGCAGGATATTCAGAGTTACATCAGCAGGACATGCGGGTCCGAACTCAGACTGAGGTTAATTAAACCCAACTTACGGGGCTTGCTCGGTGACTAGGCTATGCCCATAATCTATCCGTGCCGCTACTGACGAAGCTGGACTGATCGTTATAGCGTGACCCCTTCCGGCTAAGCATCGACGGCTCCCCGGAGTCGAGTTGGCCACCGTACGCGCTTTGGCGACGGCCCCTGCACTGAAGTATCACGCACCAATCTGACAAACACTTTAGTAAAATCAACTACGTTGGGTTTAATACAG'

def convert(seq):
    newSeq = []

    for x in seq:
        if x == "T":
            newSeq.append("U")
        else:
            newSeq.append(str(x))
    listSeq = ''.join(newSeq)
    return(listSeq)
        


RNA = convert(DNA)
print(RNA)